### ISSUE TITLE
extend openstack connector to manage floating IP addresses

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamConnectors#10] opened 2014-11-11 15:15 UTC
Some OpenStack deployments use floating IP addresses for allocating public addresses to machines.  For these infrastructures, it is necessary to manage the allocation, assignment, deallocation, and destruction of the IP addresses for machines.

For an initial implementation, I'd suggest that a boolean flag is added to the OpenStack system parameters that indicates whether floating IP addresses should be used.  If so, then for each machine a new floating IP address is allocated and assigned to the machine after it has been created.  When the machine terminates, then the IP address assignment should also be terminated and the IP address should be freed.

**Comment by schaubl** [comment] 2015-06-23 12:09
Duplicate of #34.

**Closed** 2015-06-23 12:09 UTC
Labels: duplicate, T3 Enhancement
